### PR TITLE
Make http-api work in node context

### PR DESCRIPTION
**Pull request by ajlamarc**
Continuation of https://github.com/urbit/urbit/pull/6224.  Testing in `node` context works as expected.  The call to `fetch` in `delete` returns a 204 but doesn't actually close the TCP connection, as shown in the error message below.  Is this even working as expected in the browser context?

This can be ignored with `jest --forceExit`, but I'm not sure if the ship still thinks there is a connection afterwards.

Test suite:
```js
describe('basic remote Tome tests', () => {
    let api: Urbit

    beforeAll(async () => {
        api = await Urbit.authenticate({
            ship: 'zod',
            url: 'http://localhost:8080',
            code: 'lidlut-tabwed-pillex-ridrup',
        })
    })

    test('remote Tome is ours', async () => {
        const db = await Tome.init(api, 'racket', {
            ship: 'zod',
        })
        expect(db.isOurStore()).toBe(true)
    })

    afterAll(async () => {
        await api.delete()
    })
})
```

Error:
```bash
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPWRAP

      14 |
      15 |     beforeAll(async () => {
    > 16 |         api = await Urbit.authenticate({
         |                           ^
      17 |             ship: 'zod',
      18 |             url: 'http://localhost:8080',
      19 |             code: 'lidlut-tabwed-pillex-ridrup',

      at Urbit.connect (node_modules/@holium/urbit-http-api/src/Urbit.ts:176:12)
      at Function.authenticate (node_modules/@holium/urbit-http-api/src/Urbit.ts:153:19)
      at tests/Tome.test.ts:16:27
      at step (tests/Tome.test.ts:33:23)
      at Object.next (tests/Tome.test.ts:14:53)
      at tests/Tome.test.ts:8:71
      at Object.<anonymous>.__awaiter (tests/Tome.test.ts:4:12)
      at Object.<anonymous> (tests/Tome.test.ts:15:15)
```

### CODE REVIEW

**Review by arthyn — CHANGES_REQUESTED** [review]
this looks good, but can you undo all the permissions changes?

**Comment by ajlamarc** [comment]
First time seeing that happen.  Should be good to go now!

**Comment by pkova** [comment]
There seems to be two steps required to get your test harness to exit properly. First, we need something like this for the case we're running on node: https://github.com/urbit/js-http-api/blob/9f471f806d2022e7957ea21f815852a36fd8d3ed/src/Urbit.ts#L126-L131

Node allows us to listen to some kind of exit event that allows us to achieve this.

The second problem is that using `fetch` to send the `delete` action will wait for a response. That's no good because the program is exiting. You can probably achieve something similar to `navigator.sendBeacon` in node by using `http` to make the request and just instantly doing `socket.unref()`.

Also I saw that this got merged while I was writing this up so it's probably best to make these fixes in a separate PR.

**Comment by arthyn** [comment]
I'm in the middle of integrating your changes with the fontaine fork rn. going to make us a group so we can talk about all this stuff and other frontend things.

**Comment by ajlamarc** [comment]
> There seems to be two steps required to get your test harness to exit properly. First, we need something like this for the case we're running on node: https://github.com/urbit/js-http-api/blob/9f471f806d2022e7957ea21f815852a36fd8d3ed/src/Urbit.ts#L126-L131
> 
> 
> 
> Node allows us to listen to some kind of exit event that allows us to achieve this.
> 
> 
> 
> The second problem is that using `fetch` to send the `delete` action will wait for a response. That's no good because the program is exiting. You can probably achieve something similar to `navigator.sendBeacon` in node by using `http` to make the request and just instantly doing `socket.unref()`.
> 
> 
> 
> Also I saw that this got merged while I was writing this up so it's probably best to make these fixes in a separate PR.
> 
> 

Regarding "the second issue" I made delete() async, so waiting on it should solve.  But the way you are describing sounds much better.

**Comment by ajlamarc** [comment]
> There seems to be two steps required to get your test harness to exit properly. First, we need something like this for the case we're running on node: https://github.com/urbit/js-http-api/blob/9f471f806d2022e7957ea21f815852a36fd8d3ed/src/Urbit.ts#L126-L131
> 
> 
> 
> Node allows us to listen to some kind of exit event that allows us to achieve this.
> 
> 
> 
> The second problem is that using `fetch` to send the `delete` action will wait for a response. That's no good because the program is exiting. You can probably achieve something similar to `navigator.sendBeacon` in node by using `http` to make the request and just instantly doing `socket.unref()`.
> 
> 
> 
> Also I saw that this got merged while I was writing this up so it's probably best to make these fixes in a separate PR.
> 
> 

Regarding "the second issue" I made delete() async, so waiting on it should solve.  But the way you are describing sounds much better.

**Pull request merged**
